### ISSUE TITLE
购物车和个人中心问题

### ISSUE THREAD

**Issue by moRanou** [yucccc/vue-mall#12]
拉下运行的代码，每次点购物车或者个人中心，都要我登录，尽管我已经注册登录了，只要我一点购物车或者个人中心，又会跳转到登录页面。

**Comment by SummerGC** [comment]
我也遇到了这个问题。。。

**Comment by SummerGC** [comment]
希望大佬改进一下下！！

**Comment by yucccc** [comment]
已经修改了 原因是修改了api 忘了提交到服务器 导致路径找不到 @SummerGC @moRanou
