### ISSUE TITLE
请问我打包部署到tomcat上运行为什么是空白的

### ISSUE THREAD

**Issue by fighhin** [yucccc/vue-mall#15]
我用cnpm run build 打的包,部署到服务器的tomcat上,我看调试台好像上请求路由的问题,请问这个怎么解决

**Comment by yucccc** [comment]
你看下接口是不是有问题 默认情况下是是请求的根路径 要么设置下转发 要么把静态文件作为后端的静态路径

**Comment by fighhin** [comment]
我能不能把后台改成java,然后实现前后端分离的项目?

**Comment by yucccc** [comment]
@fighhin 具体可以看下这个项目[https://github.com/Exrick/xmall-front](https://github.com/Exrick/xmall-front) 前端基于我这个项目 后端使用的是java

**Comment by fighhin** [comment]
好的,谢谢
