### ISSUE TITLE
您好，我想重新开发一个后台，我在看您请求后台数据那块遇到了一些问题，我能加您私聊吗

### ISSUE THREAD

**Issue by lugungun** [yucccc/vue-mall#9]

**Comment by yucccc** [comment]
你指的后台是？

**Comment by lugungun** [comment]
就是，如果我想做一个其他商城，那些数据我该如何获取呢

**Comment by yucccc** [comment]
可以自己定义或者爬取别人的数据




| |
cyt
邮箱：13450003105@163.com
|

签名由 网易邮箱大师 定制

在2018年02月05日 19:01，lugungun 写道：

就是，如果我想做一个其他商城，那些数据我该如何获取呢
